<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1KMDQFU" failures="2" tests="19" name="com.Equarz.Testcases.Homepagelinkstest" time="70.760" errors="0" timestamp="2023-10-09T15:03:05 IST" skipped="0">
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="featureproducttest" time="3.671"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="latestproductstest" time="3.792"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="BSTtest" time="3.710"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="RTPtest" time="3.897"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="Profileinfotest" time="2.926"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="trackordertest" time="3.060"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="refundpolicytest" time="3.945"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="returnpolicytest" time="2.710">
    <failure message="expected [http://e-quarz.com/return-poli] but found [http://e-quarz.com/return-policy]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [http://e-quarz.com/return-poli] but found [http://e-quarz.com/return-policy]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.Pageobjects.Homepagelinks.verifyreturnpolicy(Homepagelinks.java:126)
at com.Equarz.Testcases.Homepagelinkstest.returnpolicytest(Homepagelinkstest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- returnpolicytest -->
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="cancellationpolicytest" time="3.290"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="supporttickettest" time="3.443"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="twittertest" time="4.025">
    <failure message="expected [https://twitter.com/i/flow/login?redirect_after_login=%2F%3Flang%3Den-] but found [https://twitter.com/i/flow/login?redirect_after_login=%2F%3Flang%3Den-in]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://twitter.com/i/flow/login?redirect_after_login=%2F%3Flang%3Den-] but found [https://twitter.com/i/flow/login?redirect_after_login=%2F%3Flang%3Den-in]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.Pageobjects.Homepagelinks.verifytwitter(Homepagelinks.java:151)
at com.Equarz.Testcases.Homepagelinkstest.twittertest(Homepagelinkstest.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- twittertest -->
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="linkedintest" time="4.051"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="Googletest" time="4.890"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="pintresttest" time="4.181"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="instatest" time="3.304"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="facebooktest" time="4.056"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="termstest" time="3.311"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="privacytest" time="3.378"/>
  <testcase classname="com.Equarz.Testcases.Homepagelinkstest" name="logotest" time="5.120"/>
</testsuite> <!-- com.Equarz.Testcases.Homepagelinkstest -->
